# Check :
# https://docs.astral.sh/ruff/configuration/
# For refrance!
line-length = 120
indent-width = 4


# https://docs.astral.sh/ruff/rules/
# https://docs.astral.sh/ruff/settings/#lint
[lint]
select = [
  "E",
  "W",
  "I",
  "D",
] # Include errors (E), warnings (W), flake8 rules (F), isort (I), pydocstyle(D)
ignore = [
  "ANN", # Flake8-annotations (Ruff's version of type checking)
  "TCH", # Type-checking blocks (let Ty handle imports)
] # Optionally ignore specific rules, e.g., ["E501"] to ignore line length

[lint.pydocstyle]
convention = "google" # Accepts: "google", "numpy", or "pep257".


[format]
quote-style = "double"       # Your formatting setting
indent-style = "space"
docstring-code-format = true
# preview = true
#
# [analyze]
# detect-string-imports = true
